version: '3.8'

services:
  traefik:
    image: traefik:v3.5.1
    container_name: traefik
    command:
      - "--api.insecure=true"      # Allow insecure access to dashboard
      - "--api.dashboard=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
      - "--entrypoints.web.http.redirections.entryPoint.scheme=https"
      - "--certificatesresolvers.letsencrypt.acme.httpchallenge=true"
      - "--certificatesresolvers.letsencrypt.acme.httpchallenge.entrypoint=web"
      - "--certificatesresolvers.letsencrypt.acme.email=your-email@example.com"
      - "--certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json"
      - "--log.level=DEBUG"
    ports:
      - "80:80"
      - "443:443"
      - "3080:8080"  # Dashboard port
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./letsencrypt:/letsencrypt"
    labels:
      - "traefik.enable=true"
      # Global CORS middleware
      - "traefik.http.middlewares.cors-config.headers.accesscontrolallowmethods=GET,OPTIONS,PUT,POST"
      - "traefik.http.middlewares.cors-config.headers.accesscontrolallowheaders=*"
      - "traefik.http.middlewares.cors-config.headers.accesscontrolalloworiginlist=https://healthsharer.live"
      - "traefik.http.middlewares.cors-config.headers.accesscontrolmaxage=100"
      - "traefik.http.middlewares.cors-config.headers.addvaryheader=true"
      # Dashboard configuration
      - "traefik.http.routers.dashboard.rule=Host(`traefik.healthsharer.live`)"
      - "traefik.http.routers.dashboard.service=api@internal"
      - "traefik.http.routers.dashboard.entrypoints=websecure"
      - "traefik.http.routers.dashboard.tls.certresolver=letsencrypt"
      - "traefik.http.routers.dashboard.priority=30"
    networks:
      - healthsharer
  watchtower:
    image: containrrr/watchtower:latest
    container_name: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 30 --cleanup
    restart: unless-stopped
    networks:
      - healthsharer

  identity:
    image: primeng16/healthsharer:identity-service
    container_name: identity_service
    expose:
      - "5036"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - MessageQueue_HostName=message_queue
      - MessageQueue_Username=guest
      - MessageQueue_Password=guest
      - Vault_Token=Your_vault_token_here
    networks:
      - healthsharer
    labels:
      - "traefik.enable=true"
      # API endpoints
      #- "traefik.http.routers.identity-api.rule=Host(`api.healthsharer.live`) && PathPrefix(`/users`)"
      #- "traefik.http.routers.identity-api.entrypoints=websecure"
      #- "traefik.http.routers.identity-api.tls.certresolver=letsencrypt"
      #- "traefik.http.routers.identity-api.middlewares=cors-config"
      #- "traefik.http.routers.identity-api.service=identity-api"
      #- "traefik.http.services.identity-api.loadbalancer.server.port=5036"
      # OAuth endpoints on auth subdomain
      - "traefik.http.routers.identity-oauth.rule=Host(`auth.healthsharer.live`)"
      - "traefik.http.routers.identity-oauth.entrypoints=websecure"
      - "traefik.http.routers.identity-oauth.tls.certresolver=letsencrypt"
      - "traefik.http.routers.identity-oauth.middlewares=cors-config"
      - "traefik.http.routers.identity-oauth.service=identity-oauth"
    restart: unless-stopped
  permission:
    image: primeng16/healthsharer:permission-service
    container_name: permission_service
    expose:
      - "5067"
      - "7291"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - MessageQueue_HostName=message_queue
      - MessageQueue_Username=guest
      - MessageQueue_Password=guest
    networks:
      - healthsharer
    labels:
      - "traefik.enable=false"
      - "traefik.http.routers.permission.rule=Host(`api.healthsharer.live`) && PathPrefix(`/permission`)"
      - "traefik.http.routers.permission.entrypoints=websecure"
      - "traefik.http.routers.permission.tls.certresolver=letsencrypt"
      - "traefik.http.services.permission.loadbalancer.server.port=5067"
      - "traefik.http.routers.permission.middlewares=cors-config"
    restart: unless-stopped
  file:
    image: primeng16/healthsharer:file-service
    container_name: file_service
    expose:
      - "5198"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - MessageQueue_HostName=message_queue
      - MessageQueue_Username=guest
      - MessageQueue_Password=guest
    networks:
      - healthsharer
    labels:
      - "traefik.enable=false"
      - "traefik.http.routers.file.rule=Host(`api.healthsharer.live`) && PathPrefix(`/file`)"
      - "traefik.http.services.file.loadbalancer.server.port=5198"
      - "traefik.http.routers.file.middlewares=cors-config"
  fileprocessor:
    image: primeng16/healthsharer:file-process-service
    container_name: file_process_service
    expose:
      - "5126"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - MessageQueue_HostName=message_queue
      - MessageQueue_Username=guest
      - MessageQueue_Password=guest
    networks:
      - healthsharer
    labels:
      - "traefik.enable=false"
      - "traefik.http.routers.fileprocessor.rule=Host(`api.healthsharer.live`) && PathPrefix(`/fileprocessor`)"
      - "traefik.http.services.fileprocessor.loadbalancer.server.port=5126"
      - "traefik.http.routers.fileprocessor.middlewares=cors-config"
    restart: unless-stopped
  notification:
    image: primeng16/healthsharer:notification-service
    container_name: notification_service
    expose:
      - "5282"
    volumes:
      - "./Logs:/app/Logs"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - MessageQueue_HostName=message_queue
      - MessageQueue_Username=guest
      - MessageQueue_Password=guest
    networks:
      - healthsharer
    labels:
      - "traefik.enable=false"
      - "traefik.http.routers.notification.rule=Host(`api.healthsharer.live`) && PathPrefix(`/notification`)"
      - "traefik.http.services.notification.loadbalancer.server.port=5282"
      - "traefik.http.routers.notification.middlewares=cors-config"
    restart: unless-stopped
  gateway:
    image: primeng16/healthsharer:gateway
    container_name: gateway_service
    expose:
      - "5127"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    networks:
      - healthsharer
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.gateway.rule=Host(`api.healthsharer.live`)"
      - "traefik.http.routers.gateway.entrypoints=websecure"
      - "traefik.http.routers.gateway.tls.certresolver=letsencrypt"
      - "traefik.http.routers.gateway.middlewares=cors-config"
      - "traefik.http.services.gateway.loadbalancer.server.port=5127"
    restart: unless-stopped

  webapp:
    image: primeng16/healthsharer:webapp
    container_name: webapp_service
    ports:
      - "3000"
    environment:
      - NODE_ENV=production
    networks:
      - healthsharer
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.webapp.rule=Host(`healthsharer.live`)"
      - "traefik.http.services.webapp.loadbalancer.server.port=3000"
      - "traefik.http.routers.webapp.entrypoints=websecure"
      - "traefik.http.routers.webapp.tls.certresolver=letsencrypt"
      - "traefik.http.routers.webapp.priority=100"
    restart: unless-stopped
networks:
  healthsharer:
    external: true